/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AiSideHome: typeof import('~icons/ai/side-home')['default']
    AiSidePrompt: typeof import('~icons/ai/side-prompt')['default']
    AiSideTool: typeof import('~icons/ai/side-tool')['default']
    Content: typeof import('./src/components/Layout/Content.vue')['default']
    DialogApi: typeof import('./src/components/NaiveAPI/dialogApi.vue')['default']
    ListBar: typeof import('./src/components/Layout/ListBar.vue')['default']
    ListCard: typeof import('./src/components/Layout/ListCard.vue')['default']
    MessageApi: typeof import('./src/components/NaiveAPI/messageApi.vue')['default']
    NavBar: typeof import('./src/components/Layout/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/Layout/SideBar.vue')['default']
  }
}
