/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AiCardArrow: typeof import('~icons/ai/card-arrow')['default']
    AiCardFire: typeof import('~icons/ai/card-fire')['default']
    AiNavAvator: typeof import('~icons/ai/nav-avator')['default']
    AiNavTitle: typeof import('~icons/ai/nav-title')['default']
    AiNavWarning: typeof import('~icons/ai/nav-warning')['default']
    AiNavWechat: typeof import('~icons/ai/nav-wechat')['default']
    AiPromptArrow: typeof import('~icons/ai/prompt-arrow')['default']
    AiPromptContinue: typeof import('~icons/ai/prompt-continue')['default']
    AiPromptCopy: typeof import('~icons/ai/prompt-copy')['default']
    AiPromptRefresh: typeof import('~icons/ai/prompt-refresh')['default']
    AiPromptSend: typeof import('~icons/ai/prompt-send')['default']
    AiPromptStop: typeof import('~icons/ai/prompt-stop')['default']
    AiPromptVisible: typeof import('~icons/ai/prompt-visible')['default']
    AiSideHome: typeof import('~icons/ai/side-home')['default']
    AiSidePrompt: typeof import('~icons/ai/side-prompt')['default']
    AiSideTool: typeof import('~icons/ai/side-tool')['default']
    CardTag: typeof import('./src/components/card/CardTag.vue')['default']
    DetailCard: typeof import('./src/components/card/DetailCard.vue')['default']
    DetailHeader: typeof import('./src/components/detail/DetailHeader.vue')['default']
    DetailSelect: typeof import('./src/components/detail/DetailSelect.vue')['default']
    DialogApi: typeof import('./src/components/naiveAPI/dialogApi.vue')['default']
    DrainageModal: typeof import('./src/components/layout/DrainageModal.vue')['default']
    Feedback: typeof import('./src/components/common/Feedback.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    LoginModal: typeof import('./src/components/layout/LoginModal.vue')['default']
    MessageApi: typeof import('./src/components/naiveAPI/messageApi.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    TagList: typeof import('./src/components/common/TagList.vue')['default']
    ToolCard: typeof import('./src/components/card/ToolCard.vue')['default']
  }
}
